Refactor waves
CS3247-Game-Development-Team-6/Doodles pull request #200
Opened 2022-07-16 17:06 UTC by tanwayne890

This PR introduces
- Change `rounds` to `waveCounter`
- Rename GameManager.cs into GameStateManager.cs 
- Move `waveCounter` from GameStateManager.cs to WaveSpawner.cs
- change to egyptian brackets on some files

2022-07-17 07:38 UTC, tanwayne890 commented
forgot to make changes for another shader scene

2022-07-23 12:36 UTC, trxe requested changes
notes on documentation and some unnecessary comments, and one variable to change name of

2022-07-23 12:36 UTC, trxe commented on Assets/Scripts/GameManager/GameoverManager.cs
> +public class GameoverManager : MonoBehaviour {
nit: GameOver

2022-07-23 12:36 UTC, trxe commented on Assets/Scripts/GameManager/GameoverManager.cs
>      // everytime this is enabled
Replace with explanation of what is triggered OnEnable

2022-07-23 12:36 UTC, trxe commented on Assets/Scripts/GameManager/GameoverManager.cs
>          //yield on a new YieldInstruction that waits for seconds.
actually why did you need the 1.5s wait?

2022-07-23 12:36 UTC, trxe commented on Assets/Scripts/GameManager/GameoverManager.cs
> +    public void Retry() {
document what is re-enabled

2022-07-23 12:36 UTC, trxe commented on Assets/Scripts/GameManager/WaveSpawner.cs
>      // Update is called once per frame
remove

2022-07-23 12:36 UTC, trxe commented on Assets/Scripts/GameManager/WaveSpawner.cs
>          // stops when first time seeing tutorial
documentation: change to "Pause if player is viewing tutorial"

2022-07-23 12:36 UTC, trxe commented on Assets/Scripts/GameManager/WaveSpawner.cs
>              // disable this script
docs: change to "Disable WaveSpawner"

2022-07-23 12:36 UTC, trxe commented on Assets/Scripts/GameManager/WaveSpawner.cs
> +        //keep track of how many waves survive
docs: remove

2022-07-23 12:36 UTC, trxe commented on Assets/Scripts/Player/PlayerHealth.cs
>          // TODO: add death animation?
is this still needed?

2022-07-23 12:36 UTC, trxe commented on Assets/Scripts/Player/PlayerHealth.cs
>      // Start is called before the first frame update
remove

2022-07-23 12:36 UTC, trxe commented on Assets/Scripts/Player/PlayerHealth.cs
>      // Update is called once per frame
remove

2022-07-23 12:36 UTC, trxe commented on Assets/Scripts/UI/PauseMenu.cs
>      public static bool GameIsPaused;
```suggestion
    public static bool gameIsPaused;
```

2022-07-23 12:36 UTC, trxe commented on Assets/Scripts/UI/PauseMenu.cs
>      // Update is called once per frame
remove

2022-07-23 15:29 UTC, tanwayne890 commented on Assets/Scripts/GameManager/GameoverManager.cs
>          //yield on a new YieldInstruction that waits for seconds.
1.5s wait is to show the full camera shake

2022-07-23 15:31 UTC, tanwayne890 commented on Assets/Scripts/GameManager/GameoverManager.cs
>          //yield on a new YieldInstruction that waits for seconds.
will refactor this PauseGame() again

2022-07-23 15:46 UTC, tanwayne890 commented on Assets/Scripts/GameManager/WaveSpawner.cs
>              // disable this script
i think can just remove docs, code is straight forward

2022-07-23 15:52 UTC, tanwayne890 commented on Assets/Scripts/Player/PlayerHealth.cs
>          // TODO: add death animation?
TODO added by @Fenway17, i don't think is needed anymore

2022-07-23 15:59 UTC, tanwayne890 commented on Assets/Scripts/Player/PlayerHealth.cs
>          // TODO: add death animation?
Will remove this in the same file

```diff
    public void TakeDamage(int amount) {
        healthAmount -= amount;

        // float number between 0 and 1
        healthBar.fillAmount = healthAmount / maxHealth;

-        // TODO: add damage animation?

        if (healthAmount <= 0) {
            Die();
        }
    }

```

2022-07-23 16:06 UTC, tanwayne890 commented on Assets/Scripts/Player/PlayerHealth.cs
>      // Update is called once per frame
i will just remove Update() since it is doing nothing

2022-07-23 16:12 UTC, tanwayne890 commented on Assets/Scripts/Player/PlayerHealth.cs
>      // Update is called once per frame
`Update is called once per frame` and `Start is called before the first frame update` seem to be auto-generated when we create new scripts. Most of the scripts will have these docs.

Is there any way to remove these docs when Start() and Update() are auto generated?

2022-07-23 16:19 UTC, tanwayne890 commented on Assets/Scripts/UI/PauseMenu.cs
>      public static bool GameIsPaused;
I could not find the naming convention for static variable from https://google.github.io/styleguide/csharp-style.html. But I can see an example from the style guide:

![image](https://user-images.githubusercontent.com/58804560/180613534-a65ac5e8-70ed-4989-899c-6c07c9a3842d.png)

The first char in capital is better. WDYT?

2022-07-24 03:31 UTC, tanwayne890 commented on Assets/Scripts/GameManager/GameoverManager.cs
>      // everytime this is enabled
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/200/commits/ed2e671d7043215b75f3e44a9a90c87b33f58ca8

2022-07-24 03:32 UTC, tanwayne890 commented on Assets/Scripts/GameManager/GameoverManager.cs
>          //yield on a new YieldInstruction that waits for seconds.
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/200/commits/ef53215bb12b0f521d8b41d8ea826e51ae7d75df

2022-07-24 03:32 UTC, tanwayne890 commented on Assets/Scripts/GameManager/GameoverManager.cs
> +public class GameoverManager : MonoBehaviour {
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/200/commits/89b4bab9dc49fe72b45664e99dd48e103565e89e

2022-07-24 03:33 UTC, tanwayne890 commented on Assets/Scripts/GameManager/GameoverManager.cs
> +    public void Retry() {
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/200/commits/44d9fa6016a87e1dbdf2b67f0e9d7a1fe4f029d4

2022-07-24 03:35 UTC, tanwayne890 commented on Assets/Scripts/GameManager/WaveSpawner.cs
>          // stops when first time seeing tutorial
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/200/commits/322f86fb204bb5310456c7da0eabbae14c4136e4

2022-07-24 03:36 UTC, tanwayne890 commented on Assets/Scripts/UI/PauseMenu.cs
>      // Update is called once per frame
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/200/commits/0957f656dacd8bc2ddd92f330d94797101b5959d

2022-07-24 03:37 UTC, tanwayne890 commented on Assets/Scripts/GameManager/WaveSpawner.cs
>              // disable this script
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/200/commits/c4f888f12c59275371101f75e4e06cfe2f3a2cc2

2022-07-24 03:37 UTC, tanwayne890 commented on Assets/Scripts/GameManager/WaveSpawner.cs
> +        //keep track of how many waves survive
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/200/commits/146b2e2fa8788a1d5c94402a581129e588ec68f8

2022-07-24 03:37 UTC, tanwayne890 commented on Assets/Scripts/Player/PlayerHealth.cs
>          // TODO: add death animation?
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/200/commits/18aaad4ce77ae7b0d5625d6af00ce7d1f21eb202

2022-07-24 03:38 UTC, tanwayne890 commented on Assets/Scripts/Player/PlayerHealth.cs
>      // Update is called once per frame
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/200/commits/0ff714ecfe4ecc096035e98760d0bf47dc0a9dae

2022-07-24 03:39 UTC, tanwayne890 commented on Assets/Scripts/Player/PlayerHealth.cs
>      // Start is called before the first frame update
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/200/commits/0ff714ecfe4ecc096035e98760d0bf47dc0a9dae

2022-07-24 03:46 UTC, tanwayne890 commented on Assets/Scripts/GameManager/WaveSpawner.cs
>      // Update is called once per frame
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/200/commits/2d6d0d8f6feb24717b0a81a31e5d1ab608c57724

2022-07-24 05:51 UTC, trxe commented on Assets/Scripts/UI/PauseMenu.cs
>      public static bool GameIsPaused;
ah ok then we can keep it that way

2022-07-24 05:52 UTC, trxe commented on Assets/Scripts/GameManager/GameoverManager.cs
> +public class GameoverManager : MonoBehaviour {
Sorry for confusing, I meant GameOverManager

2022-07-24 05:56 UTC, trxe commented on Assets/Scripts/Player/PlayerHealth.cs
>      // Update is called once per frame
I think must manually remove each time we create a new script. Don't have to deliberately go and remove from all rn, but if we update a file that has we should remove.

2022-07-24 05:56 UTC, trxe commented on Assets/Scripts/GameManager/GameoverManager.cs
>      // everytime this is enabled
I think it's better to write "Enabled when game is running"

2022-07-24 14:00 UTC, trxe approved these changes
Once the remaining 2 changes are made you can merge in

2022-07-25 12:50 UTC, tanwayne890 commented on Assets/Scripts/GameManager/GameoverManager.cs
> +public class GameoverManager : MonoBehaviour {
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/200/commits/c87f8363539678c609970e6415c1565ce4437eb0

2022-07-25 12:50 UTC, tanwayne890 commented on Assets/Scripts/GameManager/GameoverManager.cs
>      // everytime this is enabled
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/200/commits/aee2e69515f7baa11755671b7f689d3ca11f7c68

2022-07-26 03:18 UTC, merged