Refactor `effect status` for enemy
CS3247-Game-Development-Team-6/Doodles pull request #206
Opened 2022-08-15 15:40 UTC by tanwayne890

- Use enum `EffectStatus` to keep track of enemy status caused by element effects.
- provide functions such as `setEffectStatus(EffectStatus)`, `getEffectStatus()` and `removeEffectStatus()` 
- refactor enemy script. Next PR: implement Scriptable Objects for enemy

Can be tested on `TowerRefactor` scene with ink auto generation to test out every element combinations.

This PR is not refactoring `ElementEffectsSystem/EffectManager`

2022-08-15 16:00 UTC, tanwayne890 commented on Assets/Scripts/ElementEffectSystem/EffectManager.cs
> -        enemy.setWeakened(true);
there are codes setting another status before `RemoveEffect()`. cant figure out why. Removed the codes for now

2022-08-15 16:00 UTC, tanwayne890 commented on Assets/ScriptableObjects/Elements/ElementInfos/WaterElement.asset
> +  effect: {fileID: 11400000, guid: a620402c788011848a12b7a2ef9ad464, type: 2}
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/205

2022-08-15 16:00 UTC, tanwayne890 commented on Assets/Scripts/ElementEffectSystem/EffectManager.cs
>          }
maybe you would suggest to put `enemy.removeEffectStatus()` below this part of code. However, it could be risky since there is no remove effect status for scorch.

Take note of this when refactoring `EffectManager`

2022-08-20 15:32 UTC, trxe requested changes
From what I understand EffectManager isn't considered fully refactored yet so it's current form is fine. Some minor edits (all in Enemy.cs)

2022-08-20 15:32 UTC, trxe commented on Assets/Scripts/Enemy/Enemy.cs
> +        none // default
Code style: All CAPS

2022-08-20 15:32 UTC, trxe commented on Assets/Scripts/Enemy/Enemy.cs
> +    public enum EffectStatus {
Move out of `Enemy` (move to line 5 right now)

2022-08-20 15:32 UTC, trxe commented on Assets/Scripts/Enemy/Enemy.cs
> +    private void setEnemyVisibility(bool isVisible) {
```suggestion
    private void SetEnemyVisibility(bool isVisible) {

```

2022-08-20 15:32 UTC, trxe commented on Assets/Scripts/Enemy/Enemy.cs
> +    void EndPath() {
```suggestion
    private void EndPath() {

```

2022-08-20 15:32 UTC, trxe commented on Assets/Scripts/Enemy/Enemy.cs
> +    void GetNextWaypoint() {
```suggestion
    private void GetNextWaypoint() {

```

2022-08-20 15:32 UTC, trxe commented on Assets/Scripts/Enemy/Enemy.cs
> +    void Update() {
```suggestion
    private void Update() {

```

2022-08-20 15:32 UTC, trxe commented on Assets/Scripts/Enemy/Enemy.cs
> +    void Start() {
```suggestion
    private void Start() {

```

2022-08-20 15:32 UTC, trxe commented on Assets/Scripts/Enemy/Enemy.cs
> +    void Die() {
```suggestion
    private void Die() {

```

2022-08-20 16:41 UTC, tanwayne890 commented on Assets/Scripts/Enemy/Enemy.cs
> +    void Update() {
![image](https://user-images.githubusercontent.com/58804560/185757556-91b47854-7ade-4de7-bc73-04c9a8d0eb2f.png)

From: https://forum.unity.com/threads/vs-or-unity-inserts-private-infront-of-void-update.482538/

2022-08-20 16:48 UTC, tanwayne890 commented on Assets/Scripts/Enemy/Enemy.cs
> +        none // default
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/206/commits/24b617879cfb35266d5c4c0308bacaef44158cc9

2022-08-20 16:48 UTC, tanwayne890 commented on Assets/Scripts/Enemy/Enemy.cs
> +    public enum EffectStatus {
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/206/commits/878304f0ebb76da1ff03ca249b22e48171d91394

2022-08-20 16:49 UTC, tanwayne890 commented on Assets/Scripts/Enemy/Enemy.cs
> +    private void setEnemyVisibility(bool isVisible) {
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/206/commits/73c2905a644835e1a637d0be31a2d1463fffc639

2022-08-20 16:49 UTC, tanwayne890 commented on Assets/Scripts/Enemy/Enemy.cs
> +    void EndPath() {
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/206/commits/672326936f42da3c1420ab92f1a53920d164fd79

2022-08-20 16:50 UTC, tanwayne890 commented on Assets/Scripts/Enemy/Enemy.cs
> +    void GetNextWaypoint() {
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/206/commits/c20356d1975fb601234c519352050266a716515c

2022-08-20 16:50 UTC, tanwayne890 commented on Assets/Scripts/Enemy/Enemy.cs
> +    void Die() {
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/206/commits/631bea2d4604c03001129e4f3d71eefb967cdb9a

2022-08-20 16:50 UTC, tanwayne890 commented on Assets/Scripts/Enemy/Enemy.cs
> +    void Start() {
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/206/commits/2ac98a591af6dec9444454575f14df50e6350316

2022-08-20 16:50 UTC, tanwayne890 commented on Assets/Scripts/Enemy/Enemy.cs
> +    void Update() {
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/206/commits/2ac98a591af6dec9444454575f14df50e6350316

2022-08-21 08:13 UTC, merged