Add spiders
CS3247-Game-Development-Team-6/Doodles pull request #208
Opened 2022-08-30 17:31 UTC by tanwayne890

This PR adds:
- `MeleeSpider`, `RangeSpider`, `IceMeleeSpider`, `IceRangeSpider`, `WaterMeleeSpider`, `WaterRangeSpider`, `FireMeleeSpider`, `FireRangeSpider` prefabs and its scriptable objects: `EnemyInfo` and `EnemyShootingInfo`
- damage recalculation for elemental spiders
- show damage text when enemy takes damage

Can use existing debug log to test whether enemy receives the correct amount of damage. Note that, enemy's HP is reduced by formula: HP - (bullet damage - DEF).

May need help on a new bug:
Saw one tower bullet on enemy, but send multiple times of damage to enemy

2022-08-30 17:46 UTC, tanwayne890 commented on Assets/Scripts/Enemy/Enemy.cs
> +    // The final outcome is enemy elements have no COMBINED element and tower elements (ElementType) have no COMBINED element.
FYI

2022-09-08 14:40 UTC, trxe requested changes
Made some suggestions to improve structure, do review and update

2022-09-08 14:40 UTC, trxe commented on Assets/Scripts/Enemy/Enemy.cs
> +        Debug.Log("take damage normal: " + amount);
Comment out debug log

2022-09-08 14:40 UTC, trxe commented on Assets/Scripts/Enemy/Enemy.cs
> +            Debug.Log("take damage more: " + amount * 150 / 100);
Comment out debug log

2022-09-08 14:40 UTC, trxe commented on Assets/Scripts/Enemy/Enemy.cs
> +    private ElementEffectType elementType;
Suggestion: Move into EnemyInfo instead of putting in the enemy class. And instead of using `ElementEffectType`, use `ElementInfo`

2022-09-08 14:40 UTC, trxe commented on Assets/Scripts/Enemy/Enemy.cs
> +            return;
```suggestion
        if (elementType == bulletElementType
            && elementType != ElementEffectType.NONE && elementType != ElementEffectType.COMBINED) {
            return;

```

2022-09-08 14:40 UTC, trxe commented on Assets/Scripts/Enemy/Enemy.cs
> +            || (elementType == ElementEffectType.ICE && bulletElementType == ElementEffectType.FIRE)) {
Hardcoded. Suggestion:
Add to class `ElementInfo` a `ElementType weakness`, and do a check `element.weakness.type == bulletElementType`

2022-09-08 14:40 UTC, trxe commented on Assets/Scripts/Enemy/EnemyInfo.cs
> +    public ElementEffectType elementType;
change to `ElementInfo`

2022-09-11 18:04 UTC, tanwayne890 commented
Fixed:
- Add to class ElementInfo a ElementType weakness
- In `EnemyInfo` & `Enemy`, ElementEffectType change to ElementInfo
- In `Enemy`, use ElementInfo to calculate received damage

2022-09-12 16:40 UTC, trxe approved these changes
once you make the edit, lgtm. thanks

2022-09-12 16:40 UTC, trxe commented on Assets/Scripts/Enemy/Enemy.cs
> +            ReduceHealth(amount * 150 / 100);
suggestion: make 150/100 a `[SerializableField] float multiplier`

2022-09-14 16:03 UTC, tanwayne890 commented on Assets/Scripts/Enemy/Enemy.cs
> +            ReduceHealth(amount * 150 / 100);
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/208/commits/143236b3b0bb0d67b3161e8271d2aad35f7ed2e5 added the multiplier into EnemyInfo (scriptable object)

2022-09-14 16:05 UTC, tanwayne890 commented on Assets/Scripts/Enemy/Enemy.cs
> +            ReduceHealth(amount * 150 / 100);
![image](https://user-images.githubusercontent.com/58804560/190205620-108a32e0-2327-45bd-b864-765e101c2aeb.png)

2022-09-14 17:06 UTC, merged