[Enemy] Add ghost & demon implementations
CS3247-Game-Development-Team-6/Doodles pull request #217
Opened 2022-09-16 08:29 UTC by tanwayne890

Close #213 

This PR adds:
- add invulnerabilities and spawn ability to `EnemyInfo`
- add a ghost level
- add Ghost to invulnerable for 3 seconds (red sphere surrounds) and has a invulnerable cooldown of 5 seconds
- add Demon to spawn 3 ghost upon death

Video showing:
- ghost immunes to damage and effects when red sphere appears
- demon spawns 3 ghost upon death, enemy number increases as well (see top right)

video sent to tele, too large to send here

2022-09-16 08:38 UTC, tanwayne890 commented on Assets/Scripts/Enemy/Enemy.cs
>  }
previously was `EffectStatus`, but now is `Status` contains effect status and unique status (invulnerable)

2022-09-16 08:38 UTC, tanwayne890 commented on Assets/Scripts/Enemy/Enemy.cs
> +        }
When the enemy with spawn ability dies, spawn the mobs. Here need to set the current `waypoint index` to the new mobs for movement

2022-09-16 08:38 UTC, tanwayne890 commented on Assets/Scripts/Enemy/Enemy.cs
> +        }
invulnerable has a `duration`. after the duration, enemy becomes vulnerable for a period of time which is `cooldown`

2022-09-21 10:02 UTC, tanwayne890 commented
Added a fix to separate between the spawn: https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/217/commits/ea3c8d711f1fcc657d2e30e74f9904aec5e61541

2022-09-21 10:46 UTC, tanwayne890 commented
ready for review!

2022-09-25 05:51 UTC, trxe requested changes
Please fix the suggested points, and after tonight's call we can discuss a bit on abstracting out the Enemy functions if possible.

2022-09-25 05:51 UTC, trxe commented on Assets/Scripts/Enemy/Enemy.cs
> +    INVUlNERABLE, // immune to everything
```suggestion
    INVULNERABLE, // immune to everything

```

2022-09-25 05:51 UTC, trxe commented on Assets/Scripts/Enemy/Enemy.cs
> +        transform.GetChild(4).gameObject.SetActive(true);
two issues:

1. visible through fog:

![image](https://user-images.githubusercontent.com/23572486/192130233-f33ddf98-3529-4504-bcd0-6e68d7099cc4.png)

2. hardcoding:

for now, instead of hardcoding the child index, search for the gameobject by name or keep a private reference to it please

2022-09-25 05:51 UTC, trxe commented on Assets/Scripts/Enemy/Enemy.cs
> +        transform.GetChild(4).gameObject.SetActive(false);
same as above

2022-09-25 05:51 UTC, trxe commented on Assets/Scripts/Enemy/Enemy.cs
> +    private void SpawnWhenDeath(GameObject _prefab, Vector3 _spawnPosition, Vector3 minRange, Vector3 maxRange, int _spawnCount) {
If we have time, we should discuss how to make Enemy a parent class and all implementations of Enemy such as this one inherit from Enemy instead. If not the enemy class will be cluttered with the methods for all the types of Enemies we make

2022-09-25 06:02 UTC, trxe commented on Assets/Scripts/Enemy/EnemyInfo.cs
> +    public bool isSpawnable;
```suggestion
    public bool spawnsOnDeath;
```

2022-10-04 10:23 UTC, tanwayne890 commented on Assets/Scripts/Enemy/Enemy.cs
> +    INVUlNERABLE, // immune to everything
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/217/commits/5f4df28c433932577272dc39212a71b7c907e112

2022-10-04 10:24 UTC, tanwayne890 commented on Assets/Scripts/Enemy/Enemy.cs
> +        transform.GetChild(4).gameObject.SetActive(true);
both fixed. no.1 in https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/217/commits/5b4038e7cff42846f7befc73c4c7027e1d6d054c
no.2 in https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/217/commits/4ae8743b648a100088947f78cccf201a5fc62eea

2022-10-04 10:32 UTC, tanwayne890 commented on Assets/Scripts/Enemy/Enemy.cs
> +    private void SpawnWhenDeath(GameObject _prefab, Vector3 _spawnPosition, Vector3 minRange, Vector3 maxRange, int _spawnCount) {
Idea similar to tower? like EnemyInfo <- (implements) Enemy <- (extends) CustomEnemy

After I developed laser tower using our tower framework, probably have better ideas to implement enemy

2022-10-04 10:32 UTC, tanwayne890 commented on Assets/Scripts/Enemy/EnemyInfo.cs
> +    public bool isSpawnable;
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/217/commits/31a35cbca8e02543cbdc66d6c734fb2d5b2b3607

2022-10-05 06:43 UTC, trxe approved these changes
Is working, but may need to revamp the Enemy implementation in the future as it is getting cluttered.

2022-10-12 15:22 UTC, tanwayne890 commented
Waiting for ghost and demon model

2022-10-14 03:21 UTC, merged