Dev tower damage mechanics
CS3247-Game-Development-Team-6/Doodles pull request #220
Opened 2022-09-25 09:45 UTC by Timothyoung97

This PR is to add tower damage mechanics for each existing tower. Reviews can test the mechanics under `TowerDamageDevScene`.

Main Features:
- Provides a function for an enemy to decrement the health of a tower: `Tower.cs:83 DecreaseHealth(float amount)`.
- Add a UI button to fix a tower that's being damaged.
- Add health bar indication for tower's health.

Mini Features:
- Add smoke effect when the tower is fully damaged.
- Add sound effects when the tower is fully damaged.
- Add basic tooltip information to the fix tower UI button.

**Major Changes:**
- `TowerInfo.cs`: Add tower damage mechanics variables, such as health, health decay rate, etc.
- `Tower.cs`: Add supporting mechanics for tower damage.

2022-09-26 22:52 UTC, trxe requested changes
Cannot run on my local branch, try making the prescribed changes

2022-09-26 22:52 UTC, trxe commented on Assets/Scripts/Towers/Tower.cs
> +        this.smokePrefab.transform.SetParent(transform);
Not working. Most `towerInfo`s don't have the smokePrefab, causing errors to be thrown here. I suggest putting the prefabs that you need into the `TowerManager` as `SerializedField`s.

2022-09-26 22:52 UTC, trxe commented on Assets/Scripts/Towers/Tower.cs
> +        GameObject healthBarPrefab = Instantiate(towerInfo.healthBarPrefab, transform.position, transform.rotation);
Same problem as smokePrefab

2022-09-26 22:52 UTC, trxe commented on Assets/Scripts/Towers/TowerInfo.cs
> +    public GameObject damagedSoundPrefab;
remove and put into `TowerManager` as `SerializedField`s

2022-09-26 22:52 UTC, trxe commented on Assets/Scripts/UI/Tooltip/NodeUITooltipTrigger.cs
>      }
```suggestion
        this.isFix = currentTower.IsDead();
    }

```

2022-09-26 22:52 UTC, trxe commented on Assets/Scripts/UI/Tooltip/NodeUITooltipTrigger.cs
> +    public bool isFix = false;
```suggestion
    private bool isFix = false;

```

instead of making this public, do similar to `isUpgrade` and infer from currentTower the value of  `isFix`. See my next comment below

2022-09-27 12:24 UTC, Timothyoung97 commented on Assets/Scripts/Towers/Tower.cs
> +        this.smokePrefab.transform.SetParent(transform);
Just to clarify:
- If I put the prefabs in `TowerManager`, each tower would have to access `TowerManager.instance` to retrieve these prefabs correct?

2022-09-27 12:41 UTC, Timothyoung97 commented on Assets/Scripts/UI/Tooltip/NodeUITooltipTrigger.cs
> +    public bool isFix = false;
Paiseh, I think the naming of this variable is a bit wrong, it should be `isFixButton`. 

It is a flag for the `NodeUITooltipTrigger.cs` to format the content for `fixbutton` only.

![image](https://user-images.githubusercontent.com/62177572/192528949-b9e0de62-3878-4fe7-baea-a54ef4723b1d.png)

2022-09-27 13:14 UTC, Timothyoung97 commented
## Important Note

- After merging, we have to assign the following prefabs found in `Assets/Prefabs/TowerAssets/Prefabs/Towers/Misc/` to `GameMaster's TowerManager`:
  - `TowerDamageSound.prefab` -> `Sound Effect Prefab`
  - `TowerHealthCanvas` -> `Health Bar Prefab`
  - `TowerSmoke` -> `Smoke Effect Prefab`

2022-09-27 23:35 UTC, tanwayne890 commented
merged into integrating-dialogs

2022-09-27 23:35 UTC, closed without merging