Scene loading
CS3247-Game-Development-Team-6/Doodles pull request #344
Opened 2022-10-26 14:40 UTC by tanwayne890

start from `Menu-beta`, click "New Game" 
--> Tutorial dialogue
--> Tutorial level
--> Win
--> Spider dialogue
...

2022-10-30 13:18 UTC, trxe requested changes
fix some hardcoding and readability issues first

2022-10-30 13:18 UTC, trxe commented on Assets/Scripts/UI/LoadingUI.cs
> +
hardcoding will be a problem when scene names change, could you make a SerializableField list instead to lookup?

2022-10-30 13:18 UTC, trxe commented on Assets/Scripts/UI/MainMenu.cs
> +        if (latestSceneIndex % 2 == 0) {
add helper functions `isDialogueIndex` and `getNextDialogueName` and `getNextChapterName` for better readability and in case next time the indices are no longer odd/even respectively

2022-10-31 12:50 UTC, tanwayne890 commented on Assets/Scripts/UI/MainMenu.cs
> +        if (latestSceneIndex % 2 == 0) {
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/344/commits/989563ba27737436667a1a277a1b0a8ee0f14f3d

2022-10-31 12:52 UTC, tanwayne890 commented on Assets/Scripts/UI/LoadingUI.cs
> +
use both static variable and scriptable infos (mapInfos) : https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/344/commits/dfd8f806570ebbb7f925e98338b9e7d997ab3337

2022-11-01 11:43 UTC, trxe requested changes
can you change this first?

2022-11-01 11:43 UTC, trxe commented on Assets/Scripts/UI/LoadingUI.cs
> +        }
shouldn't be so messy
```suggestion

        for (int i = 0; i < MainMenu.staticMapInfos.Length; i++) {
             if (sceneName == MainMenu.staticMapInfos[i].dialogueSceneName) {
                 currSceneIndex = GetDialogueSceneIndex(i);
             } else if (if (sceneName == MainMenu.staticMapInfos[i].gameSceneName) {
                 currSceneIndex = GetGameSceneIndex(i);
             }
        }
        
```

later on include 
```c#
int GetDialogueSceneIndex(int lvl) => lvl *2 + 1;
int GetGameSceneIndex(int lvl) => lvl *2 + 1;
```

2022-11-01 17:14 UTC, tanwayne890 commented on Assets/Scripts/UI/LoadingUI.cs
> +        }
https://github.com/CS3247-Game-Development-Team-6/Doodles/pull/344/commits/247cad910b49a99fb03667daf52c083426aeaef6

2022-11-02 02:51 UTC, trxe requested changes
1. make a copy of every scene you've used and label it for gold, just incase merge conflict screws the scenes up after merging
2. rn the game doesn't reload from the dialogue scene after quitting in the middle of dialogue scene

2022-11-02 07:38 UTC, merged